-- Create contact_submissions table
create table public.contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text not null,
  state text not null check (state in ('Andhra Pradesh', 'Telangana')),
  message text,
  status text default 'new'
);

-- Enable Row Level Security (RLS)
alter table public.contact_submissions enable row level security;

-- Create policy to allow anonymous inserts
create policy "Enable insert for anonymous users"
on public.contact_submissions
for insert
to anon
with check (true);

-- Create policy to allow reading own submissions (optional/for admin)
create policy "Start View All Submissions For Admin"
on public.contact_submissions
for select
to anon
using (true);
